# SPDX-FileCopyrightText: © 2023 Kevin Lu
# SPDX-Licence-Identifier: GPL-3.0-or-later
name: Publish Safari userscript to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p _site
          cp storm-access.user.js _site
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v1
