# SPDX-FileCopyrightText: © 2024 Kevin Lu
# SPDX-Licence-Identifier: GPL-3.0-or-later
name: Test WebExtension
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Daily after 12:00 UTC, depending on Actions availability
    - cron: "0 12 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - macos-latest
          - macos-13
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: yarn --no-lockfile
    - run: yarn playwright install --with-deps chromium
    - run: yarn playwright test
      env:
        KONAMI_JSESSIONID: ${{ secrets.KONAMI_JSESSIONID }}
        KONAMI_CGID: ${{ secrets.KONAMI_CGID }}
        KONAMI_LT: ${{ secrets.KONAMI_LT }}
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: playwright-report-${{ matrix.os }}
        path: test/playwright-report/
